version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_DATABASE=postgres_db
      - DB_PASSWORD=password
      - DB_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres_db
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data/
      
volumes:
  postgres_db:
