apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: node-app 
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres-db
        image: postgres:13
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_PASSWORD

          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: db-demo
                key: POSTGRES_USER

          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: db-demo
                key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: node-app
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432