apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: node-app
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: nodejs-app
        image: mar97/node-postgress-app
        ports:
        - containerPort: 3000
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DB_PASSWORD

          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: app-demo
                key: POSTGRES_USER

          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: app-demo
                key: POSTGRES_DB

          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: app-demo
                key: DB_PORT

          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: app-demo
                key: DB_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: node-app
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001